### ISSUE TITLE
Add min player before activate option

### ISSUE THREAD

**Issue by JaroSound** [esx-framework/esx_whitelist#8]
Is there a way to implement "https://github.com/ESX-Org/esx_whitelist/pull/6" to the new version?

**Comment by RedAlex** [comment]
Done

**Comment by RedAlex** [comment]
1 - Have you the same error with the original version ?
2 - Your table "whitelist" is empty ?
If no can you export your table "whitelist" in your database SQL and comment with the result?

You can contact me on discord to have more fast response ===>  Alex Garcio#3364

**Comment by JaroSound** [comment]
I just removed:

--	elseif not string.match(steamID, 'steam:1') then
--		kickReason = _U('steamid_error')

And all works just fine. The problem is in the original version to.
